<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClothesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clothes')->insert([
            [
                'entity_name' => 'MUTIF',
                'article_name' => 'KAMIZARA',
                'color' => 'DARK BROWN',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'combo' => 'OLIVE - MAROON',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'keyword' => 'Smart Casual',
                'description' => "Dress buka'an depan (busui friendly) dengan model simple dan design cut & sew dan motif special di bagian bawah (rok) akan menjadikanmu tampil lebih santai namun tetap trendy, bahkan yang spesial nan nyaman serta model yang simple akan membuat ruang gerak anda leluasa namun tetap elegan",
                'slug' => 'KAMIZARA',
                'group_article' => 'group 1',
                'type_id' => '1',
                'is_active' => '1',
                'size_s' => '353000',
                'size_m' => '353000',
                'size_l' => '353000',
                'size_xl' => '353000',
                'size_xxl' => '382000',
                'size_xxxl' => '294000',
                'size_2' => '0',
                'size_4' => '0',
                'size_6' => '0',
                'size_8' => '0',
                'size_10' => '0',
                'size_12' => '0',
            ],[
                'entity_name' => 'MUTIF',
                'article_name' => 'KAMIZA',
                'color' => 'DARK BROWN',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'combo' => 'OLIVE - MAROON',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'keyword' => 'Smart Casual',
                'description' => "Baju koko model simple dipadukan bahan special yang nyaman akan membuat ruang gerak anda leluasa namun tetap elegan",
                'slug' => 'KAMIZA',
                'group_article' => 'group 1',
                'type_id' => '1',
                'is_active' => '1',
                'size_s' => '235000',
                'size_m' => '235000',
                'size_l' => '235000',
                'size_xl' => '235000',
                'size_xxl' => '255000',
                'size_xxxl' => '265000',
                'size_2' => '0',
                'size_4' => '0',
                'size_6' => '0',
                'size_8' => '0',
                'size_10' => '0',
                'size_12' => '0',
            ],[
                'entity_name' => 'MUTIF',
                'article_name' => 'LITTLE KAMIZARA',
                'color' => 'DARK BROWN',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'combo' => 'OLIVE - MAROON',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'keyword' => 'Smart Casual',
                'description' => "Dress anak dengan bukaan depan dengan variasi cut and sew, menggunakan material (kain special) cotton double beem, serta hijab dengan warna senada akan membuat anak tampil lebih cantik, cerial dan percaya diri",
                'slug' => 'LITTLE KAMIZARA',
                'group_article' => 'group 1',
                'type_id' => '2',
                'is_active' => '1',
                'size_s' => '0',
                'size_m' => '0',
                'size_l' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'size_2' => '215000, 310000',
                'size_4' => '215000, 310000',
                'size_6' => '245000, 340000',
                'size_8' => '245000, 340000',
                'size_10' => '265000, 360000',
                'size_12' => '265000, 360000',
            ],[
                'entity_name' => 'MUTIF',
                'article_name' => 'LITTLE KAMIZA',
                'color' => 'DARK BROWN',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'combo' => 'OLIVE - MAROON',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'keyword' => 'Smart Casual',
                'description' => "Baju koko anak dengan model simple yang menggunakan material kain special (double beem) akan membuat anak tampil ceria dan percaya diri",
                'slug' => 'KAMIZARA',
                'group_article' => 'group 1',
                'type_id' => '2',
                'is_active' => '1',
                'size_s' => '0',
                'size_m' => '0',
                'size_l' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'size_2' => '160000',
                'size_4' => '160000',
                'size_6' => '180000',
                'size_8' => '180000',
                'size_10' => '195000',
                'size_12' => '195000',
            ],[
                'entity_name' => 'MUTIF',
                'article_name' => 'DAISY',
                'color' => 'NAVY BLUE',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'combo' => 'OLIVE - MAROON',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'keyword' => 'Smart Casual',
                'description' => "Dress anak dengan bukaan depan dengan variasi cut and sew, menggunakan material (kain special) cotton double beem, serta hijab dengan warna senada akan membuat anak tampil lebih cantik, cerial dan percaya diri",
                'slug' => 'KAMIZARA',
                'group_article' => 'group 1',
                'type_id' => '2',
                'is_active' => '1',
                'size_s' => '0',
                'size_m' => '0',
                'size_l' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'size_2' => '215000, 310000',
                'size_4' => '215000, 310000',
                'size_6' => '245000, 340000',
                'size_8' => '245000, 340000',
                'size_10' => '265000, 360000',
                'size_12' => '265000, 360000',
            ],
        ]);
    }
}
