<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClothesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clothes')->insert([
            [
                'article_name' => 'KAMIZARA',
                'color' => 'DARK BROWN',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress buka'an depan (busui friendly) dengan model simple dan design cut & sew dan motif special di bagian bawah (rok) akan menjadikanmu tampil lebih santai namun tetap trendy, bahkan yang spesial nan nyaman serta model yang simple akan membuat ruang gerak anda leluasa namun tetap elegan",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'size_10' => '0',
                'size_12' => '0',
                'size_2' => '0',
                'size_4' => '0',
                'size_6' => '0',
                'size_8' => '0',
                'size_l' => '353000',
                'size_s' => '353000',
                'size_m' => '353000',
                'size_xl' => '353000',
                'size_xxl' => '382000',
                'size_xxxl' => '294000',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'slug' => 'KAMIZARA',
                'type_id' => 1,
            ],[
                'article_name' => 'KAMIZA',
                'color' => 'DARK BROWN',
                'combo' => 'OLIVE - MAROON',
                'description' => "Baju koko model simple dipadukan bahan special yang nyaman  akan membuat ruang gerak anda leluasa namun tetap elegan",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'size_10' => '0',
                'size_12' => '0',
                'size_2' => '0',
                'size_4' => '0',
                'size_6' => '0',
                'size_8' => '0',
                'size_l' => '235000',
                'size_s' => '235000',
                'size_m' => '235000',
                'size_xl' => '235000',
                'size_xxl' => '255000',
                'size_xxxl' => '265000',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'slug' => 'KAMIZA',
                'type_id' => 1,
            ],[
                'article_name' => 'LITTLE KAMIZARA',
                'color' => 'DARK BROWN',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress anak dengan bukaan depan dengan variasi cut and sew ,menggunakan material (kain special) cotton double beem, serta hijab dengan warna senada akan membuat anak tampil lebih cantik, ceria dan percaya diri",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'size_10' => '265000,360000',
                'size_12' => '265000,360000',
                'size_2' => '215000,310000',
                'size_4' => '215000,310000',
                'size_6' => '245000,340000',
                'size_8' => '245000,340000',
                'size_l' => '0',
                'size_s' => '0',
                'size_m' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'slug' => 'LITTLE KAMIZARA',
                'type_id' => 2,
            ],[
                'article_name' => 'LITTLE KAMIZA',
                'color' => 'DARK BROWN',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress anak dengan bukaan depan dengan variasi cut and sew ,menggunakan material (kain special) cotton double beem, serta hijab dengan warna senada akan membuat anak tampil lebih cantik, ceria dan percaya diri",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Ceria',
                'material' => 'COTTON YARN DYED DOUBLE BEEM',
                'size_10' => '195000',
                'size_12' => '195000',
                'size_2' => '160000',
                'size_4' => '160000',
                'size_6' => '180000',
                'size_8' => '180000',
                'size_l' => '0',
                'size_s' => '0',
                'size_m' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'special_feature' => 'Cut & Sew Dress with special fabrics',
                'slug' => 'LITTLE KAMIZA',
                'type_id' => 2,
            ], [
                'article_name' => 'DAISY',
                'color' => 'NAVY BLUE',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress  buka’an depan  (busui friendly) dengan model simple dan design cut & sew dan motif special bias cut  di bagian bawah (rok) akan menjadikanmu tampil  lebih santai namun tetap trendy, bahan yang special nan  nyaman serta model yang simple, akan membuat ruang gerak anda leluasa namun tetap elegan",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED & COTTON SHYMPONY',
                'size_10' => '0',
                'size_12' => '0',
                'size_2' => '0',
                'size_4' => '0',
                'size_6' => '0',
                'size_8' => '0',
                'size_l' => '407000',
                'size_s' => '407000',
                'size_m' => '407000',
                'size_xl' => '407000',
                'size_xxl' => '442000',
                'size_xxxl' => '465000',
                'special_feature' => 'Dress look 2 pcs with Bias Cut Skirt',
                'slug' => 'DAISY',
                'type_id' => 1,
            ],[
                'article_name' => 'DESTA',
                'color' => 'NAVY BLUE',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress  bukaan depan  (busui friendly) dengan model simple dan design cut & sew dan motif special bias cut  di bagian bawah (rok) akan menjadikanmu tampil  lebih santai namun tetap trendy, bahan yang special nan  nyaman serta model yang simple, akan membuat ruang gerak anda leluasa namun tetap elegan",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED & COTTON SHYMPONY',
                'size_10' => '0',
                'size_12' => '0',
                'size_2' => '0',
                'size_4' => '0',
                'size_6' => '0',
                'size_8' => '0',
                'size_l' => '255000',
                'size_s' => '255000',
                'size_m' => '255000',
                'size_xl' => '255000',
                'size_xxl' => '275000',
                'size_xxxl' => '285000',
                'special_feature' => 'Dress look 2 pcs with Bias Cut Skirt',
                'slug' => 'DESTA',
                'type_id' => 1,
            ],[
                'article_name' => 'LITTLE DAISY',
                'color' => 'NAVY BLUE',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress anak dengan bukaan depan dengan variasi tali di bagian pinggang, serta hijab dengan warna senada akan membuat anak tampil lebih cantik, ceria dan percaya diri",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED & COTTON SHYMPONY',
                'size_10' => '330000,390000',
                'size_12' => '330000,390000',
                'size_2' => '290000,335000',
                'size_4' => '290000,335000',
                'size_6' => '315000,360000',
                'size_8' => '315000,360000',
                'size_l' => '0',
                'size_s' => '0',
                'size_m' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'special_feature' => 'Dress look 2 pcs with Bias Cut Skirt',
                'slug' => 'LITTLE DAISY',
                'type_id' => 2,
            ],[
                'article_name' => 'LITTLE DESTA',
                'color' => 'NAVY BLUE',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress anak dengan bukaan depan dengan variasi tali di bagian pinggang, serta hijab dengan warna senada akan membuat anak tampil lebih cantik, ceria dan percaya diri",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED & COTTON SHYMPONY',
                'size_10' => '330000,390000',
                'size_12' => '330000,390000',
                'size_2' => '290000,335000',
                'size_4' => '290000,335000',
                'size_6' => '315000,360000',
                'size_8' => '315000,360000',
                'size_l' => '0',
                'size_s' => '0',
                'size_m' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'special_feature' => 'Cut & Sew with special fabrics',
                'slug' => 'LITTLE DAISY',
                'type_id' => 2,
            ],[
                'article_name' => 'LITTLE DESTA',
                'color' => 'NAVY BLUE',
                'combo' => 'OLIVE - MAROON',
                'description' => "Dress anak dengan bukaan depan dengan variasi tali di bagian pinggang, serta hijab dengan warna senada akan membuat anak tampil lebih cantik, ceria dan percaya diri",
                'entity_name' => 'MUTIF',
                'group_article' => 'group 1',
                'is_active' => 1,
                'keyword' => 'Smart Casual',
                'material' => 'COTTON YARN DYED & COTTON SHYMPONY',
                'size_10' => '330000,390000',
                'size_12' => '330000,390000',
                'size_2' => '290000,335000',
                'size_4' => '290000,335000',
                'size_6' => '315000,360000',
                'size_8' => '315000,360000',
                'size_l' => '0',
                'size_s' => '0',
                'size_m' => '0',
                'size_xl' => '0',
                'size_xxl' => '0',
                'size_xxxl' => '0',
                'special_feature' => 'Cut & Sew with special fabrics',
                'slug' => 'LITTLE DAISY',
                'type_id' => 2,
            ]
        ]);
    }
}
